import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { getServerTranslations } from '@/lib/i18n/server'
import LanguageToggle from '@/app/components/LanguageToggle'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/app/components/ui/Card'
import { LayoutDashboard, Activity, FilePlus, MessageSquareHeart, ShieldCheck } from 'lucide-react'

interface Props {
  params: Promise<{ workspaceId: string }>
}

function formatTimeAgo(dateString: string) {
  const date = new Date(dateString)
  const now = new Date()
  const seconds = Math.floor((now.getTime() - date.getTime()) / 1000)
  
  if (seconds < 60) return 'Just now'
  
  const minutes = Math.floor(seconds / 60)
  if (minutes < 60) return `${minutes}m ago`
  
  const hours = Math.floor(minutes / 60)
  if (hours < 24) return `${hours}h ago`
  
  const days = Math.floor(hours / 24)
  if (days < 30) return `${days}d ago`
  
  return new Intl.DateTimeFormat('en', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  }).format(date)
}

export default async function WorkspaceActivityPage({ params }: Props) {
  const { workspaceId } = await params
  const supabase = await createClient()
  const { t } = await getServerTranslations()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/auth/login')

  // Fetch Forms
  const { data: forms } = await supabase
    .from('forms')
    .select('id, title, created_at, is_published')
    .eq('workspace_id', workspaceId)

  const formIds = forms?.map(f => f.id) || []

  // Fetch Responses
  const { data: responses } = await supabase
    .from('responses')
    .select('id, form_id, created_at')
    .in('form_id', formIds)

  // Map into a unified activity feed
  const timeline: any[] = []

  if (forms) {
    forms.forEach(form => {
      // Form Created Event
      timeline.push({
        id: `form_created_${form.id}`,
        type: 'form_created',
        date: form.created_at,
        title: 'New Form Created',
        description: `Form "${form.title}" was generated by AI.`,
        icon: FilePlus,
        color: 'text-indigo-500',
        bg: 'bg-indigo-100',
        href: `/dashboard/${workspaceId}/forms/${form.id}`
      })
      
      // Form Published Event (simulated near creation for timeline logic)
      if (form.is_published) {
        const pubDate = new Date(form.created_at)
        pubDate.setMinutes(pubDate.getMinutes() + 5) // Mock 5 mins later
        timeline.push({
          id: `form_published_${form.id}`,
          type: 'form_published',
          date: pubDate.toISOString(),
          title: 'Form Published',
          description: `Form "${form.title}" went live and is accepting responses.`,
          icon: ShieldCheck,
          color: 'text-emerald-500',
          bg: 'bg-emerald-100',
          href: `/dashboard/${workspaceId}/forms/${form.id}`
        })
      }
    })
  }

  if (responses) {
    responses.forEach(response => {
      const parentForm = forms?.find(f => f.id === response.form_id)
      const formName = parentForm ? parentForm.title : 'a form'
      
      timeline.push({
        id: `response_${response.id}`,
        type: 'response_received',
        date: response.created_at,
        title: 'New Response',
        description: `A new submission was received for "${formName}".`,
        icon: MessageSquareHeart,
        color: 'text-rose-500',
        bg: 'bg-rose-100',
        href: `/dashboard/${workspaceId}/forms/${response.form_id}/responses`
      })
    })
  }

  // Sort by date descending
  timeline.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())

  // Take top 50
  const recentActivities = timeline.slice(0, 50)

  return (
    <div className="flex-1 overflow-y-auto bg-slate-50 font-sans">
      <header className="sticky top-0 z-20 flex h-24 items-center justify-between border-b-2 border-slate-200 bg-white/90 px-8 backdrop-blur-md">
        <div className="flex items-center gap-6">
          <Link
            href={`/dashboard/${workspaceId}`}
            className="flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100 text-slate-600 hover:bg-slate-200 hover:text-black transition-colors shadow-sm"
          >
            <LayoutDashboard size={24} strokeWidth={3} />
          </Link>
          <div className="h-8 w-1 bg-slate-200 rounded-full"></div>
          <div>
            <h1 className="text-2xl font-black text-slate-900">{t.sidebar?.activityLog || 'Activity Log'}</h1>
            <p className="text-lg font-bold text-slate-500">Track recent events in your workspace</p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <LanguageToggle />
        </div>
      </header>

      <main className="mx-auto max-w-4xl p-8">
        <Card className="border-2 border-slate-100 shadow-sm overflow-hidden">
          <CardHeader className="border-b-2 border-slate-50 bg-white pb-6">
            <CardTitle className="text-2xl font-black text-slate-900 flex items-center gap-3">
              <Activity className="text-indigo-500" size={24} />
              Recent Activity
            </CardTitle>
            <CardDescription className="text-base font-medium mt-2 text-slate-500">
              A timeline of forms created, published, and responses received.
            </CardDescription>
          </CardHeader>
          <CardContent className="p-8">
            {recentActivities.length === 0 ? (
              <div className="text-center py-12">
                <p className="text-lg font-bold text-slate-400">No activity yet. Create a form to get started!</p>
              </div>
            ) : (
              <div className="relative border-l-2 border-slate-200 ml-4 space-y-10 py-4">
                {recentActivities.map((activity, index) => {
                  const Icon = activity.icon
                  
                  return (
                    <div key={activity.id} className="relative pl-10 group">
                      {/* Timeline dot/icon */}
                      <div className={`absolute -left-[21px] flex size-10 items-center justify-center rounded-full border-4 border-white ${activity.bg} shadow-sm group-hover:scale-110 transition-transform`}>
                        <Icon className={`h-4 w-4 ${activity.color}`} strokeWidth={3} />
                      </div>
                      
                      <div className="flex flex-col sm:flex-row sm:items-baseline gap-2 mb-1">
                        <Link href={activity.href} className="text-lg font-black text-slate-900 hover:text-indigo-600 transition-colors">
                          {activity.title}
                        </Link>
                        <span className="text-sm font-bold text-slate-400">
                          {formatTimeAgo(activity.date)}
                        </span>
                      </div>
                      <p className="text-base font-medium text-slate-500">
                        {activity.description}
                      </p>
                    </div>
                  )
                })}
              </div>
            )}
          </CardContent>
        </Card>
      </main>
    </div>
  )
}
